name: Kotlin CI with Gradle hw_5

on:
  push:
    branches: [ master, main ]
    paths:
      - 'hw_5/**'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'hw_5/**'
    
defaults:
  run:
    working-directory: hw_5

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build --info
